### ISSUE TITLE
infos web

### ISSUE THREAD

**Issue by uqam-fob** [ageei/charte#9]
Les balises pour le site web sont affichés.

Les balises devrait être ajoutées au moment de la création du site plutôt que des les inclure dans la charte elle-même.

**Comment by riclima** [comment]
Oui, merci d’avoir fait l’_issue_, j’avais remarqué ça dans b3dbc38535b5c183fdb882ee185a723cc75179d0 et b3a268374f31596b8b65fa40af0375862c2023ca. C’était la seule façon de le faire intégrer bien sans faire des grandes modifications d’un seul coup, mais au futur elles seront ajoutés dans le projet du site internet.

**Comment by uqam-fob** [comment]
p-e juste faire un Makefile côté site web qui clone/pull le dépôt et qui s'occupe de rajouter les balises?

**Comment by uqam-fob** [comment]
Corrigé avec 139eef00a849b2ba6e68920bccfa23d7a42d527b
